runtime: java11
instance_class: F2  #Or use F1
# entrypoint: 'java -jar demo/target/demo-1.0.jar'
entrypoint: 'java -jar demo-1.0.jar'

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud"
  # SPRING_DATASOURCE_URL: jdbc:mysql://34.172.6.85:3306/ecitydb?useSSL=false
  # SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/ecitydb?useSSL=false&serverTimezone=UTC
  SPRING_DATASOURCE_URL: jdbc:mysql:///ecitydb?cloudSqlInstance=electric-city-384403:us-central1:electric-city-userdatabase&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=ru$$ellh0h0h0&useSSL=false&serverTimezone=UTC

  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: ru$$ellh0h0h0
  SPRING_MAIL_USERNAME: electriccityincorporated@gmail.com
  SPRING_MAIL_PASSWORD: sxhypixihzcjevar

beta_settings:
  cloud_sql_instances: electric-city-384403:us-central1:electric-city-userdatabase

automatic_scaling:
  max_instances: 3

handlers:
- url: /.*
  script: this field is required, but ignored
